version: '3.8'

services:
  postgresql:
    image: postgres:14
    container_name: postgresql
    ports:
      - "5432:5432"
    networks:
      - kafka-net
    environment:
      POSTGRES_DB: conduktor-console
      POSTGRES_USER: conduktor
      POSTGRES_PASSWORD: some_password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - pg_data:/var/lib/postgresql/data

  conduktor-console:
    image: conduktor/conduktor-console:1.24.1
    container_name: conduktor-console
    ports:
      - "8080:8080"
    networks:
      - kafka-net
    env_file:
      - .env
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:some_password@postgresql:5432/conduktor-console"
      CDK_CLUSTERS_0_ID: "default"
      CDK_CLUSTERS_0_NAME: "My Local Kafka Cluster"
      CDK_CLUSTERS_0_COLOR: "#0013E7"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "PLAINTEXT://${KAFKA_HOST}:9092"
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://${SCHEMA_REGISTRY_HOST}:8081"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_URL: "http://${KAFKA_CONNECT_HOST}:8083"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_NAME: "full stack kafka connect"
    restart: always

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.3.2
    hostname: kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    networks:
      - kafka-net
    env_file:
      - .env
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "${KAFKA_HOST}:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://${SCHEMA_REGISTRY_HOST}:8081"
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://${SCHEMA_REGISTRY_HOST}:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars,/usr/share/confluent-hub-components
    volumes:
      - ./connectors:/etc/kafka-connect/jars/
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt debezium/debezium-connector-mysql:latest
        confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.4.0
        confluent-hub install --no-prompt confluentinc/kafka-connect-http-source:latest
        confluent-hub install --no-prompt confluentinc/kafka-connect-s3:latest
        confluent-hub install --no-prompt confluentinc/kafka-connect-s3-source:latest
        /etc/confluent/docker/run
    restart: always

networks:
  kafka-net:

volumes:
  pg_data: {}
