name: airflow_deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            sudo rm -rf seoul-transportation
            git clone git@github.com:Final-Project-Judeny/seoul-transportation.git
            (cd /home/ubuntu/seoul-transportation/airflow && echo -e "AIRFLOW_UID=50000\nAIRFLOW_GID=0" | sudo tee /home/ubuntu/seoul-transportation/airflow/.env)
            (cd /home/ubuntu/seoul-transportation/airflow && sudo docker-compose -f /home/ubuntu/seoul-transportation/airflow/docker-compose.yaml up -d)

         
